##alias svn='taskset -c 1 svn'
#alias svn='/usr/bin/time -a -o ~/.svn.wasted.time.log svn'
alias rgrep='/usr/bin/rgrep --color -n'
alias cgrep='/usr/bin/rgrep --color -n -I --exclude=tags --exclude=cscope.out --exclude=cscope.files'
alias gstatus='status --ignored'
alias ssha='ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null'
